name: DevContainer
services:
  algo:
    container_name: algo
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace/algo
      - ./.ssh/:/home/vscode/.ssh/
    stdin_open: true
    tty: true
